<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>2.0.0</Version>
    <InformationalVersion>2.0.0-alpha.3</InformationalVersion>
    <Company>Ethan Brothers</Company>
    <Product>CleanCutPDF</Product>
  </PropertyGroup>
</Project>
